"""Initial migration.

Revision ID: 2a17360def42
Revises: 
Create Date: 2022-04-13 15:56:20.754687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a17360def42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('subtitle', sa.String(), nullable=True))
    op.drop_column('blog', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('date', sa.DATETIME(), nullable=True))
    op.drop_column('blog', 'subtitle')
    # ### end Alembic commands ###
